name: Gatsby Blog with Strapi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./server

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run ci
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Push
        env:
          REPO: gatsby-blog
        run: |
          docker build -t $REPO .
          docker tag $REPO ${{secrets.DOCKER_USERNAME}}/$REPO:server
          docker push ${{secrets.DOCKER_USERNAME}}/$REPO:server
      - name: Docker Pull & Run From Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ubuntu
          key: ${{secrets.SERVER_SSH_KEY}}
          envs: GITHUB_SHA
          script: |
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker pull ${{secrets.DOCKER_USERNAME}}/gatsby-blog:server
            docker stop gatsby-server
            docker rm gatsby-server
            docker run -d --name gatsby-server -p 3000:3000 -e GMAIL_USER=${{secrets.GMAIL_USER}} -e GMAIL_PASSWORD=${{secrets.GMAIL_PASSWORD}} ${{secrets.DOCKER_USERNAME}}/gatsby-blog:server
