name: Gatsby Blog with Strapi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run ci
        run: yarn install --frozen-lockfile
        working-directory: ./server
      - name: Build
        run: yarn build
        working-directory: ./server
