name: Gatsby Blog with Strapi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: /server

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Run ci
  #       run: yarn install --frozen-lockfile
  #     - name: Build
  #       run: yarn build
  docker-build-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: fkozlicki/gatsby-blog
          tags: v1, latest
          registry: registry.hub.docker.com
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
