name: Gatsby Blog with Strapi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 14

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        working-directory: ./server
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run ci
        working-directory: ./server
        run: npm ci
      - name: Build
        working-directory: ./server
        run: npm run build
